### ISSUE TITLE
Small error in help text

### ISSUE THREAD

**Issue by dalto8** [magnus-ISU/pacman-nooby-help#1]
> To remove a package and all its unneeded dependencies,
> run 'pacman -Rn PACKAGENAME'.

The `n` in `pacman -Rn` doesn't cause uneeded deps to be removed, it indicates that pacman should not save a copy of the files in the backup array.

**Comment by magnus-ISU** [comment]
Fixed now.

I'm pretty sure there's no point in this project existing though. I'm keeping it installed for myself only, but don't think it is worth putting on the AUR.
